# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
group :development, :test do
  gem 'rspec', '~> 3.0'
  gem 'capybara', '~> 3.0'
  gem 'selenium-webdriver'
  gem 'webdrivers', '~> 4.0'
end

  gem 'rails'
